[phases.setup]
nixPkgs = ["nodejs", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates"]

[variables]
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"

[start]
cmd = "node index.js"
